name = "java-stacktrace-parser"
main = "src/index.ts"
compatibility_date = "2024-08-21"

[build]
command = "npm run build"

# Production environment
[env.production]
name = "java-stacktrace-parser-prod"
vars = { ENVIRONMENT = "production" }
route = { pattern = "stack.lihongjie.cn/*", zone_name = "lihongjie.cn" }

# Staging environment  
[env.staging]
name = "java-stacktrace-parser-staging"
vars = { ENVIRONMENT = "staging" }



